"""add id primary key to password_reset_tokens

Revision ID: bafc0b1c405c
Revises: baceb5a6a00e
Create Date: 2026-09-29 17:25:36.704818

Hand-written, not autogenerated: `token` moves from being the primary key to a plain
unique column, with a new auto-incrementing `id` as the real primary key (see the model
docstring for why — MySQL's DATETIME truncates to whole seconds, so `created_at` alone
can't reliably say which of two tokens is newest when both were issued in the same second).

Every row in this table is a short-lived, single-use token that's either already used or
will expire on its own within days — nothing here is worth an in-place data migration, so
this just drops and recreates the table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafc0b1c405c'
down_revision: Union[str, Sequence[str], None] = 'baceb5a6a00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('password_reset_tokens')
    op.create_table(
        'password_reset_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    # Only this one index for uniqueness — a separate UniqueConstraint('token') here would
    # create a second, redundant unique index doing the same job (confirmed the hard way:
    # `alembic check` flagged exactly that after this migration first shipped without it).
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)


def downgrade() -> None:
    # MySQL uses the user_id index to enforce the foreign key, so dropping that
    # index before the table fails with error 1553. Dropping the table removes
    # both indexes together with the constraint.
    op.drop_table('password_reset_tokens')
    op.create_table(
        'password_reset_tokens',
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('token'),
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
