"""initial schema

Revision ID: cb7cab4bfc8b
Revises: 
Create Date: 2026-09-29 15:26:09.116100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7cab4bfc8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('vcode', sa.String(length=32), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vcode')
    )
    op.create_index(op.f('ix_otp_codes_vcode'), 'otp_codes', ['vcode'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_matrix_json', sa.JSON(), nullable=True),
    sa.Column('two_factor', sa.Boolean(), nullable=True),
    sa.Column('sender_email', sa.String(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_rows',
    sa.Column('table_key', sa.String(length=64), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('cells_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('table_key', 'row_index')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('no', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('raised_by', sa.String(length=32), nullable=True),
    sa.Column('raised_date', sa.String(length=32), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('resolved_date', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('dept', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel_scope', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=16), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tickets')
    op.drop_table('table_rows')
    op.drop_table('sync_log')
    op.drop_table('settings')
    op.drop_index(op.f('ix_otp_codes_vcode'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
